"""Campos nuevos post y cv

Revision ID: 0a9a8cb92e9d
Revises: ea17d468768f
Create Date: 2025-08-28 01:07:19.059656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a9a8cb92e9d'
down_revision: Union[str, Sequence[str], None] = 'ea17d468768f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chargeprocess', sa.Column('form_url', sa.String(), nullable=True))
    op.add_column('postulant', sa.Column('cv_url', sa.String(), nullable=True))
    op.add_column('postulant', sa.Column('cv_drive_file_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('postulant', 'cv_drive_file_id')
    op.drop_column('postulant', 'cv_url')
    op.drop_column('chargeprocess', 'form_url')
    # ### end Alembic commands ###
