"""Actualizacion campo DNI evaluacioncv

Revision ID: 4f63cb82c24b
Revises: a9c352acaab5
Create Date: 2025-08-20 17:53:52.287660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f63cb82c24b'
down_revision: Union[str, Sequence[str], None] = 'a9c352acaab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
