"""Agregar nombre_archivo a EvaluacionCV

Revision ID: 526fdae80458
Revises: 6ce7b0d7671f
Create Date: 2025-07-31 22:52:40.924239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '526fdae80458'
down_revision: Union[str, Sequence[str], None] = '6ce7b0d7671f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluacioncv', sa.Column('nombre_archivo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluacioncv', 'nombre_archivo')
    # ### end Alembic commands ###
