"""Campo funciones en Procesos

Revision ID: 691a16425d6d
Revises: 526fdae80458
Create Date: 2025-08-13 23:51:08.263069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '691a16425d6d'
down_revision: Union[str, Sequence[str], None] = '526fdae80458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chargeprocess', sa.Column('functions', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chargeprocess', 'functions')
    # ### end Alembic commands ###
