"""Nuevo campo Chargprocess

Revision ID: 6c3b0171398f
Revises: 1ea6af8a9399
Create Date: 2025-08-28 01:38:08.955904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c3b0171398f'
down_revision: Union[str, Sequence[str], None] = '1ea6af8a9399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chargeprocess', sa.Column('form_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chargeprocess', 'form_token')
    # ### end Alembic commands ###
