"""Agregar campos url_cv, cv_procesado y cv_estado a EvaluacionCV

Revision ID: 6ce7b0d7671f
Revises: d19993b08ba7
Create Date: 2025-07-30 20:33:59.618347

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ce7b0d7671f'
down_revision: Union[str, Sequence[str], None] = 'd19993b08ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("evaluacioncv", sa.Column("url_cv", sa.String(), nullable=True))
    op.add_column("evaluacioncv", sa.Column("cv_procesado", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column("evaluacioncv", sa.Column("cv_estado", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluacioncv', 'cv_estado')
    op.drop_column('evaluacioncv', 'cv_procesado')
    op.drop_column('evaluacioncv', 'url_cv')
    # ### end Alembic commands ###
