"""Cambios menores

Revision ID: 96da5b768a8b
Revises: f2c2b64db75b
Create Date: 2025-09-07 23:51:19.378697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96da5b768a8b'
down_revision: Union[str, Sequence[str], None] = 'f2c2b64db75b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_evaluacioncv_charge_process_id'), 'evaluacioncv', ['charge_process_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluacioncv_charge_process_id'), table_name='evaluacioncv')
    # ### end Alembic commands ###
