"""Add campos adicionales a ChargeProcess

Revision ID: ad1f082dbc22
Revises: 4f63cb82c24b
Create Date: 2025-08-20 23:11:45.750585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad1f082dbc22'
down_revision: Union[str, Sequence[str], None] = '4f63cb82c24b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chargeprocess', sa.Column('is_processing', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chargeprocess', 'is_processing')
    # ### end Alembic commands ###
