"""Add nuevos campos a Postulant y EvaluacionCV

Revision ID: aea6ab1ad1b5
Revises: 
Create Date: 2025-07-29 17:04:13.385872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'aea6ab1ad1b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluacioncv', sa.Column('years_exper', sa.Float(), nullable=True))
    op.add_column('evaluacioncv', sa.Column('level_educa', sa.String(), nullable=True))
    op.add_column('evaluacioncv', sa.Column('certif', sa.String(), nullable=True))
    op.add_column('evaluacioncv', sa.Column('languages', sa.String(), nullable=True))
    op.add_column('evaluacioncv', sa.Column('differential_advantages', sa.String(), nullable=True))
    op.alter_column('evaluacioncv', 'match',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.add_column('postulant', sa.Column('years_exper', sa.Float(), nullable=True))
    op.add_column('postulant', sa.Column('level_educa', sa.String(), nullable=True))
    op.add_column('postulant', sa.Column('certif', sa.String(), nullable=True))
    op.add_column('postulant', sa.Column('languages', sa.String(), nullable=True))
    op.add_column('postulant', sa.Column('differential_advantages', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('postulant', 'differential_advantages')
    op.drop_column('postulant', 'languages')
    op.drop_column('postulant', 'certif')
    op.drop_column('postulant', 'level_educa')
    op.drop_column('postulant', 'years_exper')
    op.alter_column('evaluacioncv', 'match',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('evaluacioncv', 'differential_advantages')
    op.drop_column('evaluacioncv', 'languages')
    op.drop_column('evaluacioncv', 'certif')
    op.drop_column('evaluacioncv', 'level_educa')
    op.drop_column('evaluacioncv', 'years_exper')
    # ### end Alembic commands ###
