"""Nuevo campo EvaluacionCV

Revision ID: b5ce6c59953e
Revises: 6c3b0171398f
Create Date: 2025-08-28 01:43:37.033036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5ce6c59953e'
down_revision: Union[str, Sequence[str], None] = '6c3b0171398f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluacioncv', sa.Column('postulation_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_evaluacioncv_postulation_id'), 'evaluacioncv', ['postulation_id'], unique=False)
    op.create_foreign_key(None, 'evaluacioncv', 'postulation', ['postulation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evaluacioncv', type_='foreignkey')
    op.drop_index(op.f('ix_evaluacioncv_postulation_id'), table_name='evaluacioncv')
    op.drop_column('evaluacioncv', 'postulation_id')
    # ### end Alembic commands ###
