"""Add finalizado to ChargeProcess

Revision ID: d19993b08ba7
Revises: aea6ab1ad1b5
Create Date: 2025-07-29 17:43:16.140591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19993b08ba7'
down_revision: Union[str, Sequence[str], None] = 'aea6ab1ad1b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chargeprocess', sa.Column('end_process', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chargeprocess', 'end_process')
    # ### end Alembic commands ###
