"""Add campo funciones adicionales a EvaluacionCV

Revision ID: e4c8dc120bb6
Revises: 42b760bb1b1a
Create Date: 2025-08-14 02:19:36.611024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4c8dc120bb6'
down_revision: Union[str, Sequence[str], None] = '42b760bb1b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluacioncv', sa.Column('functions', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluacioncv', 'functions')
    # ### end Alembic commands ###
