"""Campo sombrear evaluacion cv

Revision ID: ea17d468768f
Revises: ad1f082dbc22
Create Date: 2025-08-21 14:48:34.583966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea17d468768f'
down_revision: Union[str, Sequence[str], None] = 'ad1f082dbc22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluacioncv', sa.Column('flag_shade', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluacioncv', 'flag_shade')
    # ### end Alembic commands ###
