"""Nuevos campos matchs en EvaluacionCV

Revision ID: f2c2b64db75b
Revises: b5ce6c59953e
Create Date: 2025-09-07 23:09:58.206328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2c2b64db75b'
down_revision: Union[str, Sequence[str], None] = 'b5ce6c59953e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluacioncv', sa.Column('match_eval', sa.Float(), nullable=True))
    op.add_column('evaluacioncv', sa.Column('match_total', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluacioncv', 'match_total')
    op.drop_column('evaluacioncv', 'match_eval')
    # ### end Alembic commands ###
